language: node_js
node_js:
  - stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn config set registry "https://registry.npmjs.org"
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codeclimate-test-reporter
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run build
after_script:
  - greenkeeper-lockfile-upload
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build
  on:
    tags: true
